[package]
name = "rust-par-rng"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
parse-size = { version = "1.1.0", features = ["std"] }
rand = "0.9.0"
